use master 
go


CREATE DATABASE BDORDENES_LAB_HULE
Go


USE BDORDENES_LAB_HULE

CREATE TABLE TBCREARORDEN
(
	IDORDEN INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FECHAORDEN SMALLDATETIME,
	SOLICITANTE VARCHAR (50),
	TIPOENSAYO VARCHAR (100),
	CANTMUESTRAS INT,
	TIPOMUESTRA VARCHAR (20),
	TIPOPRUEBA VARCHAR (50),
	RESPONSABLE VARCHAR (100),
	CLIENTE VARCHAR (100),
	TIPOCLIENTE VARCHAR (20),
	PRIORIDAD VARCHAR (10),
	PLAZO INT,
	FECHAESTFINAL SMALLDATETIME,
	OBSERVACIONESCREAR VARCHAR (500)
	)

	CREATE TABLE TBCERRARORDEN
(
	IDCIERRE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IDORDEN INT, 
	FECHAEJEC SMALLDATETIME,
	FECHACIERRE SMALLDATETIME,
	ESTADO VARCHAR (20),
	OBSERVACIONESCERRAR VARCHAR(500)
	
	)

	-----------------------------------------------------------------------------------------------
	
CREATE PROCEDURE [dbo].[GUARDAR_CREARORDEN]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@IDORDEN INT OUT,
@FECHAORDEN SMALLDATETIME,
@SOLICITANTE VARCHAR (50),
@TIPOENSAYO VARCHAR (100),
@CANTMUESTRAS INT,
@TIPOMUESTRA VARCHAR (20),
@TIPOPRUEBA VARCHAR (50),
@RESPONSABLE VARCHAR (100),
@CLIENTE VARCHAR (100),
@TIPOCLIENTE VARCHAR (20),
@PRIORIDAD VARCHAR (10),
@PLAZO INT,
@FECHAESTFINAL SMALLDATETIME,
@OBSERVACIONESCREAR VARCHAR (500)

AS 
	BEGIN
			INSERT INTO TBCREARORDEN(FECHAORDEN, SOLICITANTE, TIPOENSAYO, CANTMUESTRAS, TIPOMUESTRA, TIPOPRUEBA, RESPONSABLE, CLIENTE, TIPOCLIENTE, PRIORIDAD, PLAZO, FECHAESTFINAL, OBSERVACIONESCREAR)
			VALUES(@FECHAORDEN, @SOLICITANTE, @TIPOENSAYO, @CANTMUESTRAS, @TIPOMUESTRA, @TIPOPRUEBA, @RESPONSABLE, @CLIENTE, @TIPOCLIENTE, @PRIORIDAD, @PLAZO, @FECHAESTFINAL, @OBSERVACIONESCREAR)
			SELECT @IDORDEN = IDENT_CURRENT('dbo.TBCREARORDEN')

	END
	
	
-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[GUARDAR_CERRARORDEN]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@IDCIERRE INT OUT,
@IDORDEN INT, 
@FECHAEJEC SMALLDATETIME,
@FECHACIERRE SMALLDATETIME,
@ESTADO VARCHAR (20),
@OBSERVACIONESCERRAR VARCHAR(500),
@MENSAJE VARCHAR (100) OUT

AS 
	BEGIN
	      IF (EXISTS(SELECT * FROM TBCERRARORDEN WHERE IDORDEN=@IDORDEN))
			SET @MENSAJE = 'La orden ya fue cerrada'
		  ELSE
			BEGIN
				INSERT INTO TBCERRARORDEN(IDORDEN, FECHAEJEC, FECHACIERRE, ESTADO, OBSERVACIONESCERRAR)
				VALUES(@IDORDEN, @FECHAEJEC, @FECHACIERRE, @ESTADO, @OBSERVACIONESCERRAR)
				SELECT @IDCIERRE = IDENT_CURRENT('dbo.TBCERRARORDEN')
				SET @MENSAJE = 'Datos ingresados correctamente'
			END
	END

-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BUSCAR_CREARORDEN]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@IDORDEN INT,
@MSJ VARCHAR(100) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT * FROM TBCREARORDEN WHERE IDORDEN=@IDORDEN))
			SET @MSJ = 'Orden de trabajo no existe'
		ELSE
			BEGIN
				SELECT * FROM  TBCREARORDEN WHERE IDORDEN=@IDORDEN
				SET @MSJ = 'Orden de trabajo encontrada'
			END
	END

-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BUSCAR_CERRARORDEN]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@IDORDEN INT,
@MSJ VARCHAR(100) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT * FROM TBCERRARORDEN WHERE IDORDEN=@IDORDEN))
			SET @MSJ = 'Orden de trabajo no se ha cerrado'
		ELSE
			BEGIN
				SELECT * FROM  TBCERRARORDEN WHERE IDORDEN=@IDORDEN
				SET @MSJ = 'Orden de trabajo encontrada'
			END
	END

-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BUSCAR_ORDEN]

AS
SELECT * FROM TBCREARORDEN WHERE IDORDEN = (SELECT MAX(IDORDEN) FROM TBCREARORDEN) 


-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BUSCAR_CERRARORDENESTAD]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@ESTADO VARCHAR (20),
@MSJ VARCHAR(100) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT * FROM TBCERRARORDEN WHERE ESTADO=@ESTADO))
			SET @MSJ = 'Ninguna orden ha sido cerrada aún'
		ELSE
			BEGIN
				SELECT * FROM  TBCERRARORDEN AS TBC
				JOIN  TBCREARORDEN AS TBR ON TBC.IDORDEN = TBR.IDORDEN
				 WHERE (ESTADO IN (SELECT ESTADO FROM TBCERRARORDEN AS TMP GROUP BY ESTADO HAVING ESTADO = @ESTADO))
				SET @MSJ = 'Ordenes encontradas'
			END
	END

-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BUSCAR_CERRARORDENFECHCIERR]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@FECHACIERREANT SMALLDATETIME,
@FECHACIERREDESP SMALLDATETIME,
@MSJ VARCHAR(100) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT * FROM TBCERRARORDEN WHERE FECHACIERRE BETWEEN @FECHACIERREANT AND @FECHACIERREDESP))
			SET @MSJ = 'Ninguna orden ha sido cerrada aún'
		ELSE
			BEGIN
				SELECT * FROM  TBCERRARORDEN AS TBC
				JOIN  TBCREARORDEN AS TBR ON TBC.IDORDEN = TBR.IDORDEN
				 WHERE (FECHACIERRE IN (SELECT FECHACIERRE FROM TBCERRARORDEN AS TMP GROUP BY FECHACIERRE HAVING FECHACIERRE BETWEEN  @FECHACIERREANT AND @FECHACIERREDESP))
				SET @MSJ = 'Ordenes encontradas'
			END
	END

-------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BUSCAR_REPORTFECHORDEN]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@FECHAORDENANT SMALLDATETIME,
@FECHAORDENDESP SMALLDATETIME,
@MSJ VARCHAR(100) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT * FROM TBCREARORDEN WHERE FECHAORDEN BETWEEN @FECHAORDENANT AND @FECHAORDENDESP))
			SET @MSJ = 'No hay registros para la fecha indicada'
		ELSE
			BEGIN
				SELECT * FROM  TBCREARORDEN AS TBR 
				JOIN  TBCERRARORDEN AS TBC ON TBR.IDORDEN = TBC.IDORDEN 
				 WHERE (FECHAORDEN IN (SELECT FECHAORDEN FROM TBCREARORDEN AS TMP GROUP BY FECHAORDEN HAVING FECHAORDEN BETWEEN @FECHAORDENANT AND @FECHAORDENDESP))
				SET @MSJ = 'Información encontrada'
			END
	END

-------------------------------------------------------------------------------------------

SELECT * FROM TBCREARORDEN
SELECT * FROM TBCERRARORDEN
			
