'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BDORDENES_LAB_HULE")>  _
Partial Public Class DBORDENESDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertTBCREARORDEN(instance As TBCREARORDEN)
    End Sub
  Partial Private Sub UpdateTBCREARORDEN(instance As TBCREARORDEN)
    End Sub
  Partial Private Sub DeleteTBCREARORDEN(instance As TBCREARORDEN)
    End Sub
  Partial Private Sub InsertTBCERRARORDEN(instance As TBCERRARORDEN)
    End Sub
  Partial Private Sub UpdateTBCERRARORDEN(instance As TBCERRARORDEN)
    End Sub
  Partial Private Sub DeleteTBCERRARORDEN(instance As TBCERRARORDEN)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.ProyectoFinal.My.MySettings.Default.BDORDENES_LAB_HULEConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property TBCREARORDEN() As System.Data.Linq.Table(Of TBCREARORDEN)
		Get
			Return Me.GetTable(Of TBCREARORDEN)
		End Get
	End Property
	
	Public ReadOnly Property TBCERRARORDEN() As System.Data.Linq.Table(Of TBCERRARORDEN)
		Get
			Return Me.GetTable(Of TBCERRARORDEN)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_CREARORDEN")>  _
	Public Function BUSCAR_CREARORDEN(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDORDEN", DbType:="Int")> ByVal iDORDEN As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_CREARORDENResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), iDORDEN, mSJ)
		mSJ = CType(result.GetParameterValue(1),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_CREARORDENResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.GUARDAR_CREARORDEN")>  _
	Public Function GUARDAR_CREARORDEN(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDORDEN", DbType:="Int")> ByRef iDORDEN As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHAORDEN", DbType:="SmallDateTime")> ByVal fECHAORDEN As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="SOLICITANTE", DbType:="VarChar(50)")> ByVal sOLICITANTE As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TIPOENSAYO", DbType:="VarChar(100)")> ByVal tIPOENSAYO As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CANTMUESTRAS", DbType:="Int")> ByVal cANTMUESTRAS As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TIPOMUESTRA", DbType:="VarChar(20)")> ByVal tIPOMUESTRA As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TIPOPRUEBA", DbType:="VarChar(50)")> ByVal tIPOPRUEBA As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="RESPONSABLE", DbType:="VarChar(100)")> ByVal rESPONSABLE As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CLIENTE", DbType:="VarChar(100)")> ByVal cLIENTE As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TIPOCLIENTE", DbType:="VarChar(20)")> ByVal tIPOCLIENTE As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PRIORIDAD", DbType:="VarChar(10)")> ByVal pRIORIDAD As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PLAZO", DbType:="Int")> ByVal pLAZO As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHAESTFINAL", DbType:="SmallDateTime")> ByVal fECHAESTFINAL As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="OBSERVACIONESCREAR", DbType:="VarChar(500)")> ByVal oBSERVACIONESCREAR As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), iDORDEN, fECHAORDEN, sOLICITANTE, tIPOENSAYO, cANTMUESTRAS, tIPOMUESTRA, tIPOPRUEBA, rESPONSABLE, cLIENTE, tIPOCLIENTE, pRIORIDAD, pLAZO, fECHAESTFINAL, oBSERVACIONESCREAR)
		iDORDEN = CType(result.GetParameterValue(0),System.Nullable(Of Integer))
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_ORDEN")>  _
	Public Function BUSCAR_ORDEN() As ISingleResult(Of BUSCAR_ORDENResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_ORDENResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.GUARDAR_CERRARORDEN")>  _
	Public Function GUARDAR_CERRARORDEN(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDCIERRE", DbType:="Int")> ByRef iDCIERRE As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDORDEN", DbType:="Int")> ByVal iDORDEN As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHAEJEC", DbType:="SmallDateTime")> ByVal fECHAEJEC As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHACIERRE", DbType:="SmallDateTime")> ByVal fECHACIERRE As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ESTADO", DbType:="VarChar(20)")> ByVal eSTADO As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="OBSERVACIONESCERRAR", DbType:="VarChar(500)")> ByVal oBSERVACIONESCERRAR As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MENSAJE", DbType:="VarChar(100)")> ByRef mENSAJE As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), iDCIERRE, iDORDEN, fECHAEJEC, fECHACIERRE, eSTADO, oBSERVACIONESCERRAR, mENSAJE)
		iDCIERRE = CType(result.GetParameterValue(0),System.Nullable(Of Integer))
		mENSAJE = CType(result.GetParameterValue(6),String)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_REPORTFECHORDEN")>  _
	Public Function BUSCAR_REPORTFECHORDEN(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHAORDENANT", DbType:="SmallDateTime")> ByVal fECHAORDENANT As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHAORDENDESP", DbType:="SmallDateTime")> ByVal fECHAORDENDESP As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_REPORTFECHORDENResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), fECHAORDENANT, fECHAORDENDESP, mSJ)
		mSJ = CType(result.GetParameterValue(2),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_REPORTFECHORDENResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_CERRARORDEN")>  _
	Public Function BUSCAR_CERRARORDEN(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IDORDEN", DbType:="Int")> ByVal iDORDEN As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_CERRARORDENResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), iDORDEN, mSJ)
		mSJ = CType(result.GetParameterValue(1),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_CERRARORDENResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_CERRARORDENFECHCIERR")>  _
	Public Function BUSCAR_CERRARORDENFECHCIERR(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHACIERREANT", DbType:="SmallDateTime")> ByVal fECHACIERREANT As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FECHACIERREDESP", DbType:="SmallDateTime")> ByVal fECHACIERREDESP As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_CERRARORDENFECHCIERRResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), fECHACIERREANT, fECHACIERREDESP, mSJ)
		mSJ = CType(result.GetParameterValue(2),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_CERRARORDENFECHCIERRResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_CERRARORDENESTAD")>  _
	Public Function BUSCAR_CERRARORDENESTAD(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ESTADO", DbType:="VarChar(20)")> ByVal eSTADO As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_CERRARORDENESTADResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), eSTADO, mSJ)
		mSJ = CType(result.GetParameterValue(1),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_CERRARORDENESTADResult))
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TBCREARORDEN")>  _
Partial Public Class TBCREARORDEN
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDORDEN As Integer
	
	Private _FECHAORDEN As System.Nullable(Of Date)
	
	Private _SOLICITANTE As String
	
	Private _TIPOENSAYO As String
	
	Private _CANTMUESTRAS As System.Nullable(Of Integer)
	
	Private _TIPOMUESTRA As String
	
	Private _TIPOPRUEBA As String
	
	Private _RESPONSABLE As String
	
	Private _CLIENTE As String
	
	Private _TIPOCLIENTE As String
	
	Private _PRIORIDAD As String
	
	Private _PLAZO As System.Nullable(Of Integer)
	
	Private _FECHAESTFINAL As System.Nullable(Of Date)
	
	Private _OBSERVACIONESCREAR As String
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDORDENChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDORDENChanged()
    End Sub
    Partial Private Sub OnFECHAORDENChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHAORDENChanged()
    End Sub
    Partial Private Sub OnSOLICITANTEChanging(value As String)
    End Sub
    Partial Private Sub OnSOLICITANTEChanged()
    End Sub
    Partial Private Sub OnTIPOENSAYOChanging(value As String)
    End Sub
    Partial Private Sub OnTIPOENSAYOChanged()
    End Sub
    Partial Private Sub OnCANTMUESTRASChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCANTMUESTRASChanged()
    End Sub
    Partial Private Sub OnTIPOMUESTRAChanging(value As String)
    End Sub
    Partial Private Sub OnTIPOMUESTRAChanged()
    End Sub
    Partial Private Sub OnTIPOPRUEBAChanging(value As String)
    End Sub
    Partial Private Sub OnTIPOPRUEBAChanged()
    End Sub
    Partial Private Sub OnRESPONSABLEChanging(value As String)
    End Sub
    Partial Private Sub OnRESPONSABLEChanged()
    End Sub
    Partial Private Sub OnCLIENTEChanging(value As String)
    End Sub
    Partial Private Sub OnCLIENTEChanged()
    End Sub
    Partial Private Sub OnTIPOCLIENTEChanging(value As String)
    End Sub
    Partial Private Sub OnTIPOCLIENTEChanged()
    End Sub
    Partial Private Sub OnPRIORIDADChanging(value As String)
    End Sub
    Partial Private Sub OnPRIORIDADChanged()
    End Sub
    Partial Private Sub OnPLAZOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPLAZOChanged()
    End Sub
    Partial Private Sub OnFECHAESTFINALChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHAESTFINALChanged()
    End Sub
    Partial Private Sub OnOBSERVACIONESCREARChanging(value As String)
    End Sub
    Partial Private Sub OnOBSERVACIONESCREARChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDORDEN() As Integer
		Get
			Return Me._IDORDEN
		End Get
		Set
			If ((Me._IDORDEN = value)  _
						= false) Then
				Me.OnIDORDENChanging(value)
				Me.SendPropertyChanging
				Me._IDORDEN = value
				Me.SendPropertyChanged("IDORDEN")
				Me.OnIDORDENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAORDEN", DbType:="SmallDateTime")>  _
	Public Property FECHAORDEN() As System.Nullable(Of Date)
		Get
			Return Me._FECHAORDEN
		End Get
		Set
			If (Me._FECHAORDEN.Equals(value) = false) Then
				Me.OnFECHAORDENChanging(value)
				Me.SendPropertyChanging
				Me._FECHAORDEN = value
				Me.SendPropertyChanged("FECHAORDEN")
				Me.OnFECHAORDENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOLICITANTE", DbType:="VarChar(50)")>  _
	Public Property SOLICITANTE() As String
		Get
			Return Me._SOLICITANTE
		End Get
		Set
			If (String.Equals(Me._SOLICITANTE, value) = false) Then
				Me.OnSOLICITANTEChanging(value)
				Me.SendPropertyChanging
				Me._SOLICITANTE = value
				Me.SendPropertyChanged("SOLICITANTE")
				Me.OnSOLICITANTEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOENSAYO", DbType:="VarChar(100)")>  _
	Public Property TIPOENSAYO() As String
		Get
			Return Me._TIPOENSAYO
		End Get
		Set
			If (String.Equals(Me._TIPOENSAYO, value) = false) Then
				Me.OnTIPOENSAYOChanging(value)
				Me.SendPropertyChanging
				Me._TIPOENSAYO = value
				Me.SendPropertyChanged("TIPOENSAYO")
				Me.OnTIPOENSAYOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANTMUESTRAS", DbType:="Int")>  _
	Public Property CANTMUESTRAS() As System.Nullable(Of Integer)
		Get
			Return Me._CANTMUESTRAS
		End Get
		Set
			If (Me._CANTMUESTRAS.Equals(value) = false) Then
				Me.OnCANTMUESTRASChanging(value)
				Me.SendPropertyChanging
				Me._CANTMUESTRAS = value
				Me.SendPropertyChanged("CANTMUESTRAS")
				Me.OnCANTMUESTRASChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOMUESTRA", DbType:="VarChar(20)")>  _
	Public Property TIPOMUESTRA() As String
		Get
			Return Me._TIPOMUESTRA
		End Get
		Set
			If (String.Equals(Me._TIPOMUESTRA, value) = false) Then
				Me.OnTIPOMUESTRAChanging(value)
				Me.SendPropertyChanging
				Me._TIPOMUESTRA = value
				Me.SendPropertyChanged("TIPOMUESTRA")
				Me.OnTIPOMUESTRAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPRUEBA", DbType:="VarChar(50)")>  _
	Public Property TIPOPRUEBA() As String
		Get
			Return Me._TIPOPRUEBA
		End Get
		Set
			If (String.Equals(Me._TIPOPRUEBA, value) = false) Then
				Me.OnTIPOPRUEBAChanging(value)
				Me.SendPropertyChanging
				Me._TIPOPRUEBA = value
				Me.SendPropertyChanged("TIPOPRUEBA")
				Me.OnTIPOPRUEBAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="VarChar(100)")>  _
	Public Property RESPONSABLE() As String
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (String.Equals(Me._RESPONSABLE, value) = false) Then
				Me.OnRESPONSABLEChanging(value)
				Me.SendPropertyChanging
				Me._RESPONSABLE = value
				Me.SendPropertyChanged("RESPONSABLE")
				Me.OnRESPONSABLEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTE", DbType:="VarChar(100)")>  _
	Public Property CLIENTE() As String
		Get
			Return Me._CLIENTE
		End Get
		Set
			If (String.Equals(Me._CLIENTE, value) = false) Then
				Me.OnCLIENTEChanging(value)
				Me.SendPropertyChanging
				Me._CLIENTE = value
				Me.SendPropertyChanged("CLIENTE")
				Me.OnCLIENTEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOCLIENTE", DbType:="VarChar(20)")>  _
	Public Property TIPOCLIENTE() As String
		Get
			Return Me._TIPOCLIENTE
		End Get
		Set
			If (String.Equals(Me._TIPOCLIENTE, value) = false) Then
				Me.OnTIPOCLIENTEChanging(value)
				Me.SendPropertyChanging
				Me._TIPOCLIENTE = value
				Me.SendPropertyChanged("TIPOCLIENTE")
				Me.OnTIPOCLIENTEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRIORIDAD", DbType:="VarChar(10)")>  _
	Public Property PRIORIDAD() As String
		Get
			Return Me._PRIORIDAD
		End Get
		Set
			If (String.Equals(Me._PRIORIDAD, value) = false) Then
				Me.OnPRIORIDADChanging(value)
				Me.SendPropertyChanging
				Me._PRIORIDAD = value
				Me.SendPropertyChanged("PRIORIDAD")
				Me.OnPRIORIDADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLAZO", DbType:="Int")>  _
	Public Property PLAZO() As System.Nullable(Of Integer)
		Get
			Return Me._PLAZO
		End Get
		Set
			If (Me._PLAZO.Equals(value) = false) Then
				Me.OnPLAZOChanging(value)
				Me.SendPropertyChanging
				Me._PLAZO = value
				Me.SendPropertyChanged("PLAZO")
				Me.OnPLAZOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAESTFINAL", DbType:="SmallDateTime")>  _
	Public Property FECHAESTFINAL() As System.Nullable(Of Date)
		Get
			Return Me._FECHAESTFINAL
		End Get
		Set
			If (Me._FECHAESTFINAL.Equals(value) = false) Then
				Me.OnFECHAESTFINALChanging(value)
				Me.SendPropertyChanging
				Me._FECHAESTFINAL = value
				Me.SendPropertyChanged("FECHAESTFINAL")
				Me.OnFECHAESTFINALChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCREAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCREAR() As String
		Get
			Return Me._OBSERVACIONESCREAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCREAR, value) = false) Then
				Me.OnOBSERVACIONESCREARChanging(value)
				Me.SendPropertyChanging
				Me._OBSERVACIONESCREAR = value
				Me.SendPropertyChanged("OBSERVACIONESCREAR")
				Me.OnOBSERVACIONESCREARChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TBCERRARORDEN")>  _
Partial Public Class TBCERRARORDEN
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDCIERRE As Integer
	
	Private _IDORDEN As System.Nullable(Of Integer)
	
	Private _FECHAEJEC As System.Nullable(Of Date)
	
	Private _FECHACIERRE As System.Nullable(Of Date)
	
	Private _ESTADO As String
	
	Private _OBSERVACIONESCERRAR As String
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDCIERREChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDCIERREChanged()
    End Sub
    Partial Private Sub OnIDORDENChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIDORDENChanged()
    End Sub
    Partial Private Sub OnFECHAEJECChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHAEJECChanged()
    End Sub
    Partial Private Sub OnFECHACIERREChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHACIERREChanged()
    End Sub
    Partial Private Sub OnESTADOChanging(value As String)
    End Sub
    Partial Private Sub OnESTADOChanged()
    End Sub
    Partial Private Sub OnOBSERVACIONESCERRARChanging(value As String)
    End Sub
    Partial Private Sub OnOBSERVACIONESCERRARChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCIERRE", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDCIERRE() As Integer
		Get
			Return Me._IDCIERRE
		End Get
		Set
			If ((Me._IDCIERRE = value)  _
						= false) Then
				Me.OnIDCIERREChanging(value)
				Me.SendPropertyChanging
				Me._IDCIERRE = value
				Me.SendPropertyChanged("IDCIERRE")
				Me.OnIDCIERREChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int")>  _
	Public Property IDORDEN() As System.Nullable(Of Integer)
		Get
			Return Me._IDORDEN
		End Get
		Set
			If (Me._IDORDEN.Equals(value) = false) Then
				Me.OnIDORDENChanging(value)
				Me.SendPropertyChanging
				Me._IDORDEN = value
				Me.SendPropertyChanged("IDORDEN")
				Me.OnIDORDENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAEJEC", DbType:="SmallDateTime")>  _
	Public Property FECHAEJEC() As System.Nullable(Of Date)
		Get
			Return Me._FECHAEJEC
		End Get
		Set
			If (Me._FECHAEJEC.Equals(value) = false) Then
				Me.OnFECHAEJECChanging(value)
				Me.SendPropertyChanging
				Me._FECHAEJEC = value
				Me.SendPropertyChanged("FECHAEJEC")
				Me.OnFECHAEJECChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHACIERRE", DbType:="SmallDateTime")>  _
	Public Property FECHACIERRE() As System.Nullable(Of Date)
		Get
			Return Me._FECHACIERRE
		End Get
		Set
			If (Me._FECHACIERRE.Equals(value) = false) Then
				Me.OnFECHACIERREChanging(value)
				Me.SendPropertyChanging
				Me._FECHACIERRE = value
				Me.SendPropertyChanged("FECHACIERRE")
				Me.OnFECHACIERREChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESTADO", DbType:="VarChar(20)")>  _
	Public Property ESTADO() As String
		Get
			Return Me._ESTADO
		End Get
		Set
			If (String.Equals(Me._ESTADO, value) = false) Then
				Me.OnESTADOChanging(value)
				Me.SendPropertyChanging
				Me._ESTADO = value
				Me.SendPropertyChanged("ESTADO")
				Me.OnESTADOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCERRAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCERRAR() As String
		Get
			Return Me._OBSERVACIONESCERRAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCERRAR, value) = false) Then
				Me.OnOBSERVACIONESCERRARChanging(value)
				Me.SendPropertyChanging
				Me._OBSERVACIONESCERRAR = value
				Me.SendPropertyChanged("OBSERVACIONESCERRAR")
				Me.OnOBSERVACIONESCERRARChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

Partial Public Class BUSCAR_CREARORDENResult
	
	Private _IDORDEN As Integer
	
	Private _FECHAORDEN As System.Nullable(Of Date)
	
	Private _SOLICITANTE As String
	
	Private _TIPOENSAYO As String
	
	Private _CANTMUESTRAS As System.Nullable(Of Integer)
	
	Private _TIPOMUESTRA As String
	
	Private _TIPOPRUEBA As String
	
	Private _RESPONSABLE As String
	
	Private _CLIENTE As String
	
	Private _TIPOCLIENTE As String
	
	Private _PRIORIDAD As String
	
	Private _PLAZO As System.Nullable(Of Integer)
	
	Private _FECHAESTFINAL As System.Nullable(Of Date)
	
	Private _OBSERVACIONESCREAR As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int NOT NULL")>  _
	Public Property IDORDEN() As Integer
		Get
			Return Me._IDORDEN
		End Get
		Set
			If ((Me._IDORDEN = value)  _
						= false) Then
				Me._IDORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAORDEN", DbType:="SmallDateTime")>  _
	Public Property FECHAORDEN() As System.Nullable(Of Date)
		Get
			Return Me._FECHAORDEN
		End Get
		Set
			If (Me._FECHAORDEN.Equals(value) = false) Then
				Me._FECHAORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOLICITANTE", DbType:="VarChar(50)")>  _
	Public Property SOLICITANTE() As String
		Get
			Return Me._SOLICITANTE
		End Get
		Set
			If (String.Equals(Me._SOLICITANTE, value) = false) Then
				Me._SOLICITANTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOENSAYO", DbType:="VarChar(100)")>  _
	Public Property TIPOENSAYO() As String
		Get
			Return Me._TIPOENSAYO
		End Get
		Set
			If (String.Equals(Me._TIPOENSAYO, value) = false) Then
				Me._TIPOENSAYO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANTMUESTRAS", DbType:="Int")>  _
	Public Property CANTMUESTRAS() As System.Nullable(Of Integer)
		Get
			Return Me._CANTMUESTRAS
		End Get
		Set
			If (Me._CANTMUESTRAS.Equals(value) = false) Then
				Me._CANTMUESTRAS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOMUESTRA", DbType:="VarChar(20)")>  _
	Public Property TIPOMUESTRA() As String
		Get
			Return Me._TIPOMUESTRA
		End Get
		Set
			If (String.Equals(Me._TIPOMUESTRA, value) = false) Then
				Me._TIPOMUESTRA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPRUEBA", DbType:="VarChar(50)")>  _
	Public Property TIPOPRUEBA() As String
		Get
			Return Me._TIPOPRUEBA
		End Get
		Set
			If (String.Equals(Me._TIPOPRUEBA, value) = false) Then
				Me._TIPOPRUEBA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="VarChar(100)")>  _
	Public Property RESPONSABLE() As String
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (String.Equals(Me._RESPONSABLE, value) = false) Then
				Me._RESPONSABLE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTE", DbType:="VarChar(100)")>  _
	Public Property CLIENTE() As String
		Get
			Return Me._CLIENTE
		End Get
		Set
			If (String.Equals(Me._CLIENTE, value) = false) Then
				Me._CLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOCLIENTE", DbType:="VarChar(20)")>  _
	Public Property TIPOCLIENTE() As String
		Get
			Return Me._TIPOCLIENTE
		End Get
		Set
			If (String.Equals(Me._TIPOCLIENTE, value) = false) Then
				Me._TIPOCLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRIORIDAD", DbType:="VarChar(10)")>  _
	Public Property PRIORIDAD() As String
		Get
			Return Me._PRIORIDAD
		End Get
		Set
			If (String.Equals(Me._PRIORIDAD, value) = false) Then
				Me._PRIORIDAD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLAZO", DbType:="Int")>  _
	Public Property PLAZO() As System.Nullable(Of Integer)
		Get
			Return Me._PLAZO
		End Get
		Set
			If (Me._PLAZO.Equals(value) = false) Then
				Me._PLAZO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAESTFINAL", DbType:="SmallDateTime")>  _
	Public Property FECHAESTFINAL() As System.Nullable(Of Date)
		Get
			Return Me._FECHAESTFINAL
		End Get
		Set
			If (Me._FECHAESTFINAL.Equals(value) = false) Then
				Me._FECHAESTFINAL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCREAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCREAR() As String
		Get
			Return Me._OBSERVACIONESCREAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCREAR, value) = false) Then
				Me._OBSERVACIONESCREAR = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_ORDENResult
	
	Private _IDORDEN As Integer
	
	Private _FECHAORDEN As System.Nullable(Of Date)
	
	Private _SOLICITANTE As String
	
	Private _TIPOENSAYO As String
	
	Private _CANTMUESTRAS As System.Nullable(Of Integer)
	
	Private _TIPOMUESTRA As String
	
	Private _TIPOPRUEBA As String
	
	Private _RESPONSABLE As String
	
	Private _CLIENTE As String
	
	Private _TIPOCLIENTE As String
	
	Private _PRIORIDAD As String
	
	Private _PLAZO As System.Nullable(Of Integer)
	
	Private _FECHAESTFINAL As System.Nullable(Of Date)
	
	Private _OBSERVACIONESCREAR As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int NOT NULL")>  _
	Public Property IDORDEN() As Integer
		Get
			Return Me._IDORDEN
		End Get
		Set
			If ((Me._IDORDEN = value)  _
						= false) Then
				Me._IDORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAORDEN", DbType:="SmallDateTime")>  _
	Public Property FECHAORDEN() As System.Nullable(Of Date)
		Get
			Return Me._FECHAORDEN
		End Get
		Set
			If (Me._FECHAORDEN.Equals(value) = false) Then
				Me._FECHAORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOLICITANTE", DbType:="VarChar(50)")>  _
	Public Property SOLICITANTE() As String
		Get
			Return Me._SOLICITANTE
		End Get
		Set
			If (String.Equals(Me._SOLICITANTE, value) = false) Then
				Me._SOLICITANTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOENSAYO", DbType:="VarChar(100)")>  _
	Public Property TIPOENSAYO() As String
		Get
			Return Me._TIPOENSAYO
		End Get
		Set
			If (String.Equals(Me._TIPOENSAYO, value) = false) Then
				Me._TIPOENSAYO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANTMUESTRAS", DbType:="Int")>  _
	Public Property CANTMUESTRAS() As System.Nullable(Of Integer)
		Get
			Return Me._CANTMUESTRAS
		End Get
		Set
			If (Me._CANTMUESTRAS.Equals(value) = false) Then
				Me._CANTMUESTRAS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOMUESTRA", DbType:="VarChar(20)")>  _
	Public Property TIPOMUESTRA() As String
		Get
			Return Me._TIPOMUESTRA
		End Get
		Set
			If (String.Equals(Me._TIPOMUESTRA, value) = false) Then
				Me._TIPOMUESTRA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPRUEBA", DbType:="VarChar(50)")>  _
	Public Property TIPOPRUEBA() As String
		Get
			Return Me._TIPOPRUEBA
		End Get
		Set
			If (String.Equals(Me._TIPOPRUEBA, value) = false) Then
				Me._TIPOPRUEBA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="VarChar(100)")>  _
	Public Property RESPONSABLE() As String
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (String.Equals(Me._RESPONSABLE, value) = false) Then
				Me._RESPONSABLE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTE", DbType:="VarChar(100)")>  _
	Public Property CLIENTE() As String
		Get
			Return Me._CLIENTE
		End Get
		Set
			If (String.Equals(Me._CLIENTE, value) = false) Then
				Me._CLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOCLIENTE", DbType:="VarChar(20)")>  _
	Public Property TIPOCLIENTE() As String
		Get
			Return Me._TIPOCLIENTE
		End Get
		Set
			If (String.Equals(Me._TIPOCLIENTE, value) = false) Then
				Me._TIPOCLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRIORIDAD", DbType:="VarChar(10)")>  _
	Public Property PRIORIDAD() As String
		Get
			Return Me._PRIORIDAD
		End Get
		Set
			If (String.Equals(Me._PRIORIDAD, value) = false) Then
				Me._PRIORIDAD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLAZO", DbType:="Int")>  _
	Public Property PLAZO() As System.Nullable(Of Integer)
		Get
			Return Me._PLAZO
		End Get
		Set
			If (Me._PLAZO.Equals(value) = false) Then
				Me._PLAZO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAESTFINAL", DbType:="SmallDateTime")>  _
	Public Property FECHAESTFINAL() As System.Nullable(Of Date)
		Get
			Return Me._FECHAESTFINAL
		End Get
		Set
			If (Me._FECHAESTFINAL.Equals(value) = false) Then
				Me._FECHAESTFINAL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCREAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCREAR() As String
		Get
			Return Me._OBSERVACIONESCREAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCREAR, value) = false) Then
				Me._OBSERVACIONESCREAR = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_REPORTFECHORDENResult
	
	Private _IDORDEN As Integer
	
	Private _FECHAORDEN As System.Nullable(Of Date)
	
	Private _SOLICITANTE As String
	
	Private _TIPOENSAYO As String
	
	Private _CANTMUESTRAS As System.Nullable(Of Integer)
	
	Private _TIPOMUESTRA As String
	
	Private _TIPOPRUEBA As String
	
	Private _RESPONSABLE As String
	
	Private _CLIENTE As String
	
	Private _TIPOCLIENTE As String
	
	Private _PRIORIDAD As String
	
	Private _PLAZO As System.Nullable(Of Integer)
	
	Private _FECHAESTFINAL As System.Nullable(Of Date)
	
	Private _OBSERVACIONESCREAR As String
	
	Private _IDCIERRE As Integer
	
	Private _IDORDEN1 As System.Nullable(Of Integer)
	
	Private _FECHAEJEC As System.Nullable(Of Date)
	
	Private _FECHACIERRE As System.Nullable(Of Date)
	
	Private _ESTADO As String
	
	Private _OBSERVACIONESCERRAR As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int NOT NULL")>  _
	Public Property IDORDEN() As Integer
		Get
			Return Me._IDORDEN
		End Get
		Set
			If ((Me._IDORDEN = value)  _
						= false) Then
				Me._IDORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAORDEN", DbType:="SmallDateTime")>  _
	Public Property FECHAORDEN() As System.Nullable(Of Date)
		Get
			Return Me._FECHAORDEN
		End Get
		Set
			If (Me._FECHAORDEN.Equals(value) = false) Then
				Me._FECHAORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOLICITANTE", DbType:="VarChar(50)")>  _
	Public Property SOLICITANTE() As String
		Get
			Return Me._SOLICITANTE
		End Get
		Set
			If (String.Equals(Me._SOLICITANTE, value) = false) Then
				Me._SOLICITANTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOENSAYO", DbType:="VarChar(100)")>  _
	Public Property TIPOENSAYO() As String
		Get
			Return Me._TIPOENSAYO
		End Get
		Set
			If (String.Equals(Me._TIPOENSAYO, value) = false) Then
				Me._TIPOENSAYO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANTMUESTRAS", DbType:="Int")>  _
	Public Property CANTMUESTRAS() As System.Nullable(Of Integer)
		Get
			Return Me._CANTMUESTRAS
		End Get
		Set
			If (Me._CANTMUESTRAS.Equals(value) = false) Then
				Me._CANTMUESTRAS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOMUESTRA", DbType:="VarChar(20)")>  _
	Public Property TIPOMUESTRA() As String
		Get
			Return Me._TIPOMUESTRA
		End Get
		Set
			If (String.Equals(Me._TIPOMUESTRA, value) = false) Then
				Me._TIPOMUESTRA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPRUEBA", DbType:="VarChar(50)")>  _
	Public Property TIPOPRUEBA() As String
		Get
			Return Me._TIPOPRUEBA
		End Get
		Set
			If (String.Equals(Me._TIPOPRUEBA, value) = false) Then
				Me._TIPOPRUEBA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="VarChar(100)")>  _
	Public Property RESPONSABLE() As String
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (String.Equals(Me._RESPONSABLE, value) = false) Then
				Me._RESPONSABLE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTE", DbType:="VarChar(100)")>  _
	Public Property CLIENTE() As String
		Get
			Return Me._CLIENTE
		End Get
		Set
			If (String.Equals(Me._CLIENTE, value) = false) Then
				Me._CLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOCLIENTE", DbType:="VarChar(20)")>  _
	Public Property TIPOCLIENTE() As String
		Get
			Return Me._TIPOCLIENTE
		End Get
		Set
			If (String.Equals(Me._TIPOCLIENTE, value) = false) Then
				Me._TIPOCLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRIORIDAD", DbType:="VarChar(10)")>  _
	Public Property PRIORIDAD() As String
		Get
			Return Me._PRIORIDAD
		End Get
		Set
			If (String.Equals(Me._PRIORIDAD, value) = false) Then
				Me._PRIORIDAD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLAZO", DbType:="Int")>  _
	Public Property PLAZO() As System.Nullable(Of Integer)
		Get
			Return Me._PLAZO
		End Get
		Set
			If (Me._PLAZO.Equals(value) = false) Then
				Me._PLAZO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAESTFINAL", DbType:="SmallDateTime")>  _
	Public Property FECHAESTFINAL() As System.Nullable(Of Date)
		Get
			Return Me._FECHAESTFINAL
		End Get
		Set
			If (Me._FECHAESTFINAL.Equals(value) = false) Then
				Me._FECHAESTFINAL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCREAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCREAR() As String
		Get
			Return Me._OBSERVACIONESCREAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCREAR, value) = false) Then
				Me._OBSERVACIONESCREAR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCIERRE", DbType:="Int NOT NULL")>  _
	Public Property IDCIERRE() As Integer
		Get
			Return Me._IDCIERRE
		End Get
		Set
			If ((Me._IDCIERRE = value)  _
						= false) Then
				Me._IDCIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN1", DbType:="Int")>  _
	Public Property IDORDEN1() As System.Nullable(Of Integer)
		Get
			Return Me._IDORDEN1
		End Get
		Set
			If (Me._IDORDEN1.Equals(value) = false) Then
				Me._IDORDEN1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAEJEC", DbType:="SmallDateTime")>  _
	Public Property FECHAEJEC() As System.Nullable(Of Date)
		Get
			Return Me._FECHAEJEC
		End Get
		Set
			If (Me._FECHAEJEC.Equals(value) = false) Then
				Me._FECHAEJEC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHACIERRE", DbType:="SmallDateTime")>  _
	Public Property FECHACIERRE() As System.Nullable(Of Date)
		Get
			Return Me._FECHACIERRE
		End Get
		Set
			If (Me._FECHACIERRE.Equals(value) = false) Then
				Me._FECHACIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESTADO", DbType:="VarChar(20)")>  _
	Public Property ESTADO() As String
		Get
			Return Me._ESTADO
		End Get
		Set
			If (String.Equals(Me._ESTADO, value) = false) Then
				Me._ESTADO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCERRAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCERRAR() As String
		Get
			Return Me._OBSERVACIONESCERRAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCERRAR, value) = false) Then
				Me._OBSERVACIONESCERRAR = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_CERRARORDENResult
	
	Private _IDCIERRE As Integer
	
	Private _IDORDEN As System.Nullable(Of Integer)
	
	Private _FECHAEJEC As System.Nullable(Of Date)
	
	Private _FECHACIERRE As System.Nullable(Of Date)
	
	Private _ESTADO As String
	
	Private _OBSERVACIONESCERRAR As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCIERRE", DbType:="Int NOT NULL")>  _
	Public Property IDCIERRE() As Integer
		Get
			Return Me._IDCIERRE
		End Get
		Set
			If ((Me._IDCIERRE = value)  _
						= false) Then
				Me._IDCIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int")>  _
	Public Property IDORDEN() As System.Nullable(Of Integer)
		Get
			Return Me._IDORDEN
		End Get
		Set
			If (Me._IDORDEN.Equals(value) = false) Then
				Me._IDORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAEJEC", DbType:="SmallDateTime")>  _
	Public Property FECHAEJEC() As System.Nullable(Of Date)
		Get
			Return Me._FECHAEJEC
		End Get
		Set
			If (Me._FECHAEJEC.Equals(value) = false) Then
				Me._FECHAEJEC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHACIERRE", DbType:="SmallDateTime")>  _
	Public Property FECHACIERRE() As System.Nullable(Of Date)
		Get
			Return Me._FECHACIERRE
		End Get
		Set
			If (Me._FECHACIERRE.Equals(value) = false) Then
				Me._FECHACIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESTADO", DbType:="VarChar(20)")>  _
	Public Property ESTADO() As String
		Get
			Return Me._ESTADO
		End Get
		Set
			If (String.Equals(Me._ESTADO, value) = false) Then
				Me._ESTADO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCERRAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCERRAR() As String
		Get
			Return Me._OBSERVACIONESCERRAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCERRAR, value) = false) Then
				Me._OBSERVACIONESCERRAR = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_CERRARORDENFECHCIERRResult
	
	Private _IDCIERRE As Integer
	
	Private _IDORDEN As System.Nullable(Of Integer)
	
	Private _FECHAEJEC As System.Nullable(Of Date)
	
	Private _FECHACIERRE As System.Nullable(Of Date)
	
	Private _ESTADO As String
	
	Private _OBSERVACIONESCERRAR As String
	
	Private _IDORDEN1 As Integer
	
	Private _FECHAORDEN As System.Nullable(Of Date)
	
	Private _SOLICITANTE As String
	
	Private _TIPOENSAYO As String
	
	Private _CANTMUESTRAS As System.Nullable(Of Integer)
	
	Private _TIPOMUESTRA As String
	
	Private _TIPOPRUEBA As String
	
	Private _RESPONSABLE As String
	
	Private _CLIENTE As String
	
	Private _TIPOCLIENTE As String
	
	Private _PRIORIDAD As String
	
	Private _PLAZO As System.Nullable(Of Integer)
	
	Private _FECHAESTFINAL As System.Nullable(Of Date)
	
	Private _OBSERVACIONESCREAR As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCIERRE", DbType:="Int NOT NULL")>  _
	Public Property IDCIERRE() As Integer
		Get
			Return Me._IDCIERRE
		End Get
		Set
			If ((Me._IDCIERRE = value)  _
						= false) Then
				Me._IDCIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int")>  _
	Public Property IDORDEN() As System.Nullable(Of Integer)
		Get
			Return Me._IDORDEN
		End Get
		Set
			If (Me._IDORDEN.Equals(value) = false) Then
				Me._IDORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAEJEC", DbType:="SmallDateTime")>  _
	Public Property FECHAEJEC() As System.Nullable(Of Date)
		Get
			Return Me._FECHAEJEC
		End Get
		Set
			If (Me._FECHAEJEC.Equals(value) = false) Then
				Me._FECHAEJEC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHACIERRE", DbType:="SmallDateTime")>  _
	Public Property FECHACIERRE() As System.Nullable(Of Date)
		Get
			Return Me._FECHACIERRE
		End Get
		Set
			If (Me._FECHACIERRE.Equals(value) = false) Then
				Me._FECHACIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESTADO", DbType:="VarChar(20)")>  _
	Public Property ESTADO() As String
		Get
			Return Me._ESTADO
		End Get
		Set
			If (String.Equals(Me._ESTADO, value) = false) Then
				Me._ESTADO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCERRAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCERRAR() As String
		Get
			Return Me._OBSERVACIONESCERRAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCERRAR, value) = false) Then
				Me._OBSERVACIONESCERRAR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN1", DbType:="Int NOT NULL")>  _
	Public Property IDORDEN1() As Integer
		Get
			Return Me._IDORDEN1
		End Get
		Set
			If ((Me._IDORDEN1 = value)  _
						= false) Then
				Me._IDORDEN1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAORDEN", DbType:="SmallDateTime")>  _
	Public Property FECHAORDEN() As System.Nullable(Of Date)
		Get
			Return Me._FECHAORDEN
		End Get
		Set
			If (Me._FECHAORDEN.Equals(value) = false) Then
				Me._FECHAORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOLICITANTE", DbType:="VarChar(50)")>  _
	Public Property SOLICITANTE() As String
		Get
			Return Me._SOLICITANTE
		End Get
		Set
			If (String.Equals(Me._SOLICITANTE, value) = false) Then
				Me._SOLICITANTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOENSAYO", DbType:="VarChar(100)")>  _
	Public Property TIPOENSAYO() As String
		Get
			Return Me._TIPOENSAYO
		End Get
		Set
			If (String.Equals(Me._TIPOENSAYO, value) = false) Then
				Me._TIPOENSAYO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANTMUESTRAS", DbType:="Int")>  _
	Public Property CANTMUESTRAS() As System.Nullable(Of Integer)
		Get
			Return Me._CANTMUESTRAS
		End Get
		Set
			If (Me._CANTMUESTRAS.Equals(value) = false) Then
				Me._CANTMUESTRAS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOMUESTRA", DbType:="VarChar(20)")>  _
	Public Property TIPOMUESTRA() As String
		Get
			Return Me._TIPOMUESTRA
		End Get
		Set
			If (String.Equals(Me._TIPOMUESTRA, value) = false) Then
				Me._TIPOMUESTRA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPRUEBA", DbType:="VarChar(50)")>  _
	Public Property TIPOPRUEBA() As String
		Get
			Return Me._TIPOPRUEBA
		End Get
		Set
			If (String.Equals(Me._TIPOPRUEBA, value) = false) Then
				Me._TIPOPRUEBA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="VarChar(100)")>  _
	Public Property RESPONSABLE() As String
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (String.Equals(Me._RESPONSABLE, value) = false) Then
				Me._RESPONSABLE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTE", DbType:="VarChar(100)")>  _
	Public Property CLIENTE() As String
		Get
			Return Me._CLIENTE
		End Get
		Set
			If (String.Equals(Me._CLIENTE, value) = false) Then
				Me._CLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOCLIENTE", DbType:="VarChar(20)")>  _
	Public Property TIPOCLIENTE() As String
		Get
			Return Me._TIPOCLIENTE
		End Get
		Set
			If (String.Equals(Me._TIPOCLIENTE, value) = false) Then
				Me._TIPOCLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRIORIDAD", DbType:="VarChar(10)")>  _
	Public Property PRIORIDAD() As String
		Get
			Return Me._PRIORIDAD
		End Get
		Set
			If (String.Equals(Me._PRIORIDAD, value) = false) Then
				Me._PRIORIDAD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLAZO", DbType:="Int")>  _
	Public Property PLAZO() As System.Nullable(Of Integer)
		Get
			Return Me._PLAZO
		End Get
		Set
			If (Me._PLAZO.Equals(value) = false) Then
				Me._PLAZO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAESTFINAL", DbType:="SmallDateTime")>  _
	Public Property FECHAESTFINAL() As System.Nullable(Of Date)
		Get
			Return Me._FECHAESTFINAL
		End Get
		Set
			If (Me._FECHAESTFINAL.Equals(value) = false) Then
				Me._FECHAESTFINAL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCREAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCREAR() As String
		Get
			Return Me._OBSERVACIONESCREAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCREAR, value) = false) Then
				Me._OBSERVACIONESCREAR = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_CERRARORDENESTADResult
	
	Private _IDCIERRE As Integer
	
	Private _IDORDEN As System.Nullable(Of Integer)
	
	Private _FECHAEJEC As System.Nullable(Of Date)
	
	Private _FECHACIERRE As System.Nullable(Of Date)
	
	Private _ESTADO As String
	
	Private _OBSERVACIONESCERRAR As String
	
	Private _IDORDEN1 As Integer
	
	Private _FECHAORDEN As System.Nullable(Of Date)
	
	Private _SOLICITANTE As String
	
	Private _TIPOENSAYO As String
	
	Private _CANTMUESTRAS As System.Nullable(Of Integer)
	
	Private _TIPOMUESTRA As String
	
	Private _TIPOPRUEBA As String
	
	Private _RESPONSABLE As String
	
	Private _CLIENTE As String
	
	Private _TIPOCLIENTE As String
	
	Private _PRIORIDAD As String
	
	Private _PLAZO As System.Nullable(Of Integer)
	
	Private _FECHAESTFINAL As System.Nullable(Of Date)
	
	Private _OBSERVACIONESCREAR As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCIERRE", DbType:="Int NOT NULL")>  _
	Public Property IDCIERRE() As Integer
		Get
			Return Me._IDCIERRE
		End Get
		Set
			If ((Me._IDCIERRE = value)  _
						= false) Then
				Me._IDCIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN", DbType:="Int")>  _
	Public Property IDORDEN() As System.Nullable(Of Integer)
		Get
			Return Me._IDORDEN
		End Get
		Set
			If (Me._IDORDEN.Equals(value) = false) Then
				Me._IDORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAEJEC", DbType:="SmallDateTime")>  _
	Public Property FECHAEJEC() As System.Nullable(Of Date)
		Get
			Return Me._FECHAEJEC
		End Get
		Set
			If (Me._FECHAEJEC.Equals(value) = false) Then
				Me._FECHAEJEC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHACIERRE", DbType:="SmallDateTime")>  _
	Public Property FECHACIERRE() As System.Nullable(Of Date)
		Get
			Return Me._FECHACIERRE
		End Get
		Set
			If (Me._FECHACIERRE.Equals(value) = false) Then
				Me._FECHACIERRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESTADO", DbType:="VarChar(20)")>  _
	Public Property ESTADO() As String
		Get
			Return Me._ESTADO
		End Get
		Set
			If (String.Equals(Me._ESTADO, value) = false) Then
				Me._ESTADO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCERRAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCERRAR() As String
		Get
			Return Me._OBSERVACIONESCERRAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCERRAR, value) = false) Then
				Me._OBSERVACIONESCERRAR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDORDEN1", DbType:="Int NOT NULL")>  _
	Public Property IDORDEN1() As Integer
		Get
			Return Me._IDORDEN1
		End Get
		Set
			If ((Me._IDORDEN1 = value)  _
						= false) Then
				Me._IDORDEN1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAORDEN", DbType:="SmallDateTime")>  _
	Public Property FECHAORDEN() As System.Nullable(Of Date)
		Get
			Return Me._FECHAORDEN
		End Get
		Set
			If (Me._FECHAORDEN.Equals(value) = false) Then
				Me._FECHAORDEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOLICITANTE", DbType:="VarChar(50)")>  _
	Public Property SOLICITANTE() As String
		Get
			Return Me._SOLICITANTE
		End Get
		Set
			If (String.Equals(Me._SOLICITANTE, value) = false) Then
				Me._SOLICITANTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOENSAYO", DbType:="VarChar(100)")>  _
	Public Property TIPOENSAYO() As String
		Get
			Return Me._TIPOENSAYO
		End Get
		Set
			If (String.Equals(Me._TIPOENSAYO, value) = false) Then
				Me._TIPOENSAYO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANTMUESTRAS", DbType:="Int")>  _
	Public Property CANTMUESTRAS() As System.Nullable(Of Integer)
		Get
			Return Me._CANTMUESTRAS
		End Get
		Set
			If (Me._CANTMUESTRAS.Equals(value) = false) Then
				Me._CANTMUESTRAS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOMUESTRA", DbType:="VarChar(20)")>  _
	Public Property TIPOMUESTRA() As String
		Get
			Return Me._TIPOMUESTRA
		End Get
		Set
			If (String.Equals(Me._TIPOMUESTRA, value) = false) Then
				Me._TIPOMUESTRA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPRUEBA", DbType:="VarChar(50)")>  _
	Public Property TIPOPRUEBA() As String
		Get
			Return Me._TIPOPRUEBA
		End Get
		Set
			If (String.Equals(Me._TIPOPRUEBA, value) = false) Then
				Me._TIPOPRUEBA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="VarChar(100)")>  _
	Public Property RESPONSABLE() As String
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (String.Equals(Me._RESPONSABLE, value) = false) Then
				Me._RESPONSABLE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTE", DbType:="VarChar(100)")>  _
	Public Property CLIENTE() As String
		Get
			Return Me._CLIENTE
		End Get
		Set
			If (String.Equals(Me._CLIENTE, value) = false) Then
				Me._CLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOCLIENTE", DbType:="VarChar(20)")>  _
	Public Property TIPOCLIENTE() As String
		Get
			Return Me._TIPOCLIENTE
		End Get
		Set
			If (String.Equals(Me._TIPOCLIENTE, value) = false) Then
				Me._TIPOCLIENTE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRIORIDAD", DbType:="VarChar(10)")>  _
	Public Property PRIORIDAD() As String
		Get
			Return Me._PRIORIDAD
		End Get
		Set
			If (String.Equals(Me._PRIORIDAD, value) = false) Then
				Me._PRIORIDAD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLAZO", DbType:="Int")>  _
	Public Property PLAZO() As System.Nullable(Of Integer)
		Get
			Return Me._PLAZO
		End Get
		Set
			If (Me._PLAZO.Equals(value) = false) Then
				Me._PLAZO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHAESTFINAL", DbType:="SmallDateTime")>  _
	Public Property FECHAESTFINAL() As System.Nullable(Of Date)
		Get
			Return Me._FECHAESTFINAL
		End Get
		Set
			If (Me._FECHAESTFINAL.Equals(value) = false) Then
				Me._FECHAESTFINAL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBSERVACIONESCREAR", DbType:="VarChar(500)")>  _
	Public Property OBSERVACIONESCREAR() As String
		Get
			Return Me._OBSERVACIONESCREAR
		End Get
		Set
			If (String.Equals(Me._OBSERVACIONESCREAR, value) = false) Then
				Me._OBSERVACIONESCREAR = value
			End If
		End Set
	End Property
End Class
