'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BDUSUARIO_LAB_HULE")>  _
Partial Public Class DBUsuarioDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.ProyectoFinal.My.MySettings.Default.BDUSUARIO_LAB_HULEConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property TBJEFATURA() As System.Data.Linq.Table(Of TBJEFATURA)
		Get
			Return Me.GetTable(Of TBJEFATURA)
		End Get
	End Property
	
	Public ReadOnly Property TBTECNICO() As System.Data.Linq.Table(Of TBTECNICO)
		Get
			Return Me.GetTable(Of TBTECNICO)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_JEFATURA")>  _
	Public Function BUSCAR_JEFATURA(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="USUARIO", DbType:="VarChar(20)")> ByVal uSUARIO As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_JEFATURAResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), uSUARIO, mSJ)
		mSJ = CType(result.GetParameterValue(1),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_JEFATURAResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.BUSCAR_TECNICO")>  _
	Public Function BUSCAR_TECNICO(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="USUARIO", DbType:="VarChar(20)")> ByVal uSUARIO As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MSJ", DbType:="VarChar(100)")> ByRef mSJ As String) As ISingleResult(Of BUSCAR_TECNICOResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), uSUARIO, mSJ)
		mSJ = CType(result.GetParameterValue(1),String)
		Return CType(result.ReturnValue,ISingleResult(Of BUSCAR_TECNICOResult))
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TBJEFATURA")>  _
Partial Public Class TBJEFATURA
	
	Private _IDUSUARIO As Integer
	
	Private _USUARIO As String
	
	Private _NOMBRE As String
	
	Private _DEPARTAMENTO As String
	
	Private _EXTENSION As Integer
	
	Private _EMAIL As String
	
	Private _CONTRASENA As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDUSUARIO", DbType:="Int NOT NULL")>  _
	Public Property IDUSUARIO() As Integer
		Get
			Return Me._IDUSUARIO
		End Get
		Set
			If ((Me._IDUSUARIO = value)  _
						= false) Then
				Me._IDUSUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USUARIO", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property USUARIO() As String
		Get
			Return Me._USUARIO
		End Get
		Set
			If (String.Equals(Me._USUARIO, value) = false) Then
				Me._USUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NOMBRE", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NOMBRE() As String
		Get
			Return Me._NOMBRE
		End Get
		Set
			If (String.Equals(Me._NOMBRE, value) = false) Then
				Me._NOMBRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTAMENTO", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DEPARTAMENTO() As String
		Get
			Return Me._DEPARTAMENTO
		End Get
		Set
			If (String.Equals(Me._DEPARTAMENTO, value) = false) Then
				Me._DEPARTAMENTO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXTENSION", DbType:="Int NOT NULL")>  _
	Public Property EXTENSION() As Integer
		Get
			Return Me._EXTENSION
		End Get
		Set
			If ((Me._EXTENSION = value)  _
						= false) Then
				Me._EXTENSION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me._EMAIL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONTRASENA", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CONTRASENA() As String
		Get
			Return Me._CONTRASENA
		End Get
		Set
			If (String.Equals(Me._CONTRASENA, value) = false) Then
				Me._CONTRASENA = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TBTECNICO")>  _
Partial Public Class TBTECNICO
	
	Private _IDUSUARIO As Integer
	
	Private _USUARIO As String
	
	Private _NOMBRE As String
	
	Private _DEPARTAMENTO As String
	
	Private _EXTENSION As Integer
	
	Private _EMAIL As String
	
	Private _CONTRASENA As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDUSUARIO", DbType:="Int NOT NULL")>  _
	Public Property IDUSUARIO() As Integer
		Get
			Return Me._IDUSUARIO
		End Get
		Set
			If ((Me._IDUSUARIO = value)  _
						= false) Then
				Me._IDUSUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USUARIO", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property USUARIO() As String
		Get
			Return Me._USUARIO
		End Get
		Set
			If (String.Equals(Me._USUARIO, value) = false) Then
				Me._USUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NOMBRE", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NOMBRE() As String
		Get
			Return Me._NOMBRE
		End Get
		Set
			If (String.Equals(Me._NOMBRE, value) = false) Then
				Me._NOMBRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTAMENTO", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DEPARTAMENTO() As String
		Get
			Return Me._DEPARTAMENTO
		End Get
		Set
			If (String.Equals(Me._DEPARTAMENTO, value) = false) Then
				Me._DEPARTAMENTO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXTENSION", DbType:="Int NOT NULL")>  _
	Public Property EXTENSION() As Integer
		Get
			Return Me._EXTENSION
		End Get
		Set
			If ((Me._EXTENSION = value)  _
						= false) Then
				Me._EXTENSION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me._EMAIL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONTRASENA", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CONTRASENA() As String
		Get
			Return Me._CONTRASENA
		End Get
		Set
			If (String.Equals(Me._CONTRASENA, value) = false) Then
				Me._CONTRASENA = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_JEFATURAResult
	
	Private _IDUSUARIO As Integer
	
	Private _USUARIO As String
	
	Private _NOMBRE As String
	
	Private _DEPARTAMENTO As String
	
	Private _EXTENSION As Integer
	
	Private _EMAIL As String
	
	Private _CONTRASENA As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDUSUARIO", DbType:="Int NOT NULL")>  _
	Public Property IDUSUARIO() As Integer
		Get
			Return Me._IDUSUARIO
		End Get
		Set
			If ((Me._IDUSUARIO = value)  _
						= false) Then
				Me._IDUSUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USUARIO", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property USUARIO() As String
		Get
			Return Me._USUARIO
		End Get
		Set
			If (String.Equals(Me._USUARIO, value) = false) Then
				Me._USUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NOMBRE", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NOMBRE() As String
		Get
			Return Me._NOMBRE
		End Get
		Set
			If (String.Equals(Me._NOMBRE, value) = false) Then
				Me._NOMBRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTAMENTO", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DEPARTAMENTO() As String
		Get
			Return Me._DEPARTAMENTO
		End Get
		Set
			If (String.Equals(Me._DEPARTAMENTO, value) = false) Then
				Me._DEPARTAMENTO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXTENSION", DbType:="Int NOT NULL")>  _
	Public Property EXTENSION() As Integer
		Get
			Return Me._EXTENSION
		End Get
		Set
			If ((Me._EXTENSION = value)  _
						= false) Then
				Me._EXTENSION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me._EMAIL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONTRASENA", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CONTRASENA() As String
		Get
			Return Me._CONTRASENA
		End Get
		Set
			If (String.Equals(Me._CONTRASENA, value) = false) Then
				Me._CONTRASENA = value
			End If
		End Set
	End Property
End Class

Partial Public Class BUSCAR_TECNICOResult
	
	Private _IDUSUARIO As Integer
	
	Private _USUARIO As String
	
	Private _NOMBRE As String
	
	Private _DEPARTAMENTO As String
	
	Private _EXTENSION As Integer
	
	Private _EMAIL As String
	
	Private _CONTRASENA As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDUSUARIO", DbType:="Int NOT NULL")>  _
	Public Property IDUSUARIO() As Integer
		Get
			Return Me._IDUSUARIO
		End Get
		Set
			If ((Me._IDUSUARIO = value)  _
						= false) Then
				Me._IDUSUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USUARIO", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property USUARIO() As String
		Get
			Return Me._USUARIO
		End Get
		Set
			If (String.Equals(Me._USUARIO, value) = false) Then
				Me._USUARIO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NOMBRE", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NOMBRE() As String
		Get
			Return Me._NOMBRE
		End Get
		Set
			If (String.Equals(Me._NOMBRE, value) = false) Then
				Me._NOMBRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPARTAMENTO", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DEPARTAMENTO() As String
		Get
			Return Me._DEPARTAMENTO
		End Get
		Set
			If (String.Equals(Me._DEPARTAMENTO, value) = false) Then
				Me._DEPARTAMENTO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXTENSION", DbType:="Int NOT NULL")>  _
	Public Property EXTENSION() As Integer
		Get
			Return Me._EXTENSION
		End Get
		Set
			If ((Me._EXTENSION = value)  _
						= false) Then
				Me._EXTENSION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me._EMAIL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONTRASENA", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CONTRASENA() As String
		Get
			Return Me._CONTRASENA
		End Get
		Set
			If (String.Equals(Me._CONTRASENA, value) = false) Then
				Me._CONTRASENA = value
			End If
		End Set
	End Property
End Class
